#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = $HOME/.config/hypr/wallpapers.sh

######################################
### Embed external config settings ###
######################################

source = vars.conf
source = monitors.conf
source = input.conf
source = styling.conf