- name: Install hyprland with other visual components
  community.general.pacman:
    name:
      - hyprland
      - hyprlock
      - hyprshot
      - hypridle
      - hyprshot
      - xdg-desktop-portal-hyprland                    
      - waybar                  
    state: present
  when: ansible_facts['os_family'] == "Archlinux"
  tags: [desktop, hyprland]

# - name: Install mvppaper for video backgrounds
#   kewlfft.aur.aur:
#     name:
#       - mpvpaper                     
#     use: yay
#     state: present
#   become: no
#   when: ansible_os_family == "Archlinux"
#   tags: [desktop, hyprland, wallpaper]