- name: "Setup stow dotfiles"
  ansible.builtin.shell: "stow -v -d ../../config-files -R -t ~ private"
  register: stow_result
  changed_when: "'LINK' in stow_result.stderr or 'UNLINK' in stow_result.stderr"
  tags: [configs]