#################
### AUTOSTART ###
#################

exec-once = hyprpaper
exec-once = waybar

######################################
### Embed external config settings ###
######################################

source = vars.conf
source = monitors.conf
source = input.conf
source = styling.conf