#####################
### LOOK AND FEEL ###
#####################

env = XCURSOR_SIZE,0
env = XCURSOR_THEME,

general {
	gaps_in = 6
	gaps_out = 10
	border_size = 2
	col.active_border = rgb(255,118,118)
	col.inactive_border = rgb(90,5,5)
	resize_on_border = true
	allow_tearing = false
	layout = dwindle
}

decoration {
	rounding = 8
	rounding_power = 2
	dim_inactive = false
	
	shadow {
		enabled = true
		range = 8
		render_power = 2
		color = rgb(90,5,5)
	}
	
	blur {
		enabled = true
		size = 2
		passes = 2
		vibrancy = 4 
	}
}

dwindle {
	pseudotile = true    
	preserve_split = true
}

master {
	new_status = master
}

misc {
	force_default_wallpaper = false
	disable_hyprland_logo = false
}