- name: Setup development environment
  hosts: localhost
  tasks:
    - name: "Install ides"
      include_tasks: ../common/tasks/install-ides.yml
      tags: ides
    - name: "Install zsh plugins"
      include_tasks: tasks/install-zsh-plugins.yml
      tags: ides
      